### ISSUE TITLE
Default mime type: text/plain vs application/octet-stream

### ISSUE THREAD

**Issue by mgrahamjo** [cloudflare/kv-asset-handler#124]
The current default mime type for files with unrecognized or missing extensions is `text/plain`, but the suggestion was made in https://github.com/cloudflare/kv-asset-handler/pull/121 to change it to `application/octet-stream`. The [MIME RFC](https://tools.ietf.org/html/rfc2045#section-5.2) states that the default should be `text/plain`, but the actual [HTTP spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html#sec7.2.1) states that when the Content-Type header is missing, clients should treat it as `application/octet-stream`. 

One consideration is that browsers don't attempt to render `application/octet-stream`; they download it to the filesystem instead.

**Comment by SukkaW** [comment]
> One consideration is that browsers don't attempt to render application/octet-stream; they download it to the filesystem instead.

When `Content-Disposition: attachment` is presented, browser will download the file as well (ignoring the mime type).

**Comment by ekanna** [comment]
How to change this default value to "application/octet-stream"?
My file is supposed to be downloaded automatically but it is rendering as text in Firefox as content-type is text/plain.

Thanks

**Comment by SukkaW** [comment]
> How to change this default value to "application/octet-stream"?

https://github.com/cloudflare/kv-asset-handler#defaultmimetype-optional

`kv-asset-handler` provides a configuration.

**Comment by ekanna** [comment]
Thank you. Now it's working fine.
