### ISSUE TITLE
Check HTTP Method after mapRequestToAsset

### ISSUE THREAD

**Issue by oliverpool** [cloudflare/kv-asset-handler#151]
Currently in `getAssetFromKV` the HTTP Method is checked before the call to `mapRequestToAsset`:

https://github.com/cloudflare/kv-asset-handler/blob/3df430c248d2d8711ac69ad6497d7a32610c9e4e/src/index.ts#L96-L111

I suggest to check the HTTP method **after** this.

--- 

In my case, I want to send an e-mail on a webhook (which is a POST call from an external service - payment provider for instance).
I store my email template along my static site, so that it is uploaded to the KV store.
I want to retrieve the template using `getAssetFromKV`, (replacing the request path using `mapRequestToAsset`), however it fails because the method check is done before this.

I currently have an ugly hack, creating a new pseudo-event with a fresh GET request...

---

I don't see any drawback to moving this check after the `if` block (`mapRequestToAsset` is not supposed to have any side-effect, so calling it before failing should not be a big deal9.

I would be happy to make a PR if you think this is not a bad idea.

**Comment by aqueenan** [comment]
@oliverpool I ran into the same problem and agree with your suggested solution.

For anyone experiencing the same problem, here is a workaround:

```
async function getResponseFromKV(event, url) {
  let options = {
    mapRequestToAsset: req => new Request(url),
    cacheControl: {
      bypassCache: DEBUG,
    }
  }

  if (event.request.method === 'POST') {
    options.cacheControl.bypassCache = true // Prevents event.waitUntil() from being called
    event = {
      request: new Request(url)
    }
  }

  return await getAssetFromKV(event, options)
}
```

**Comment by oliverpool** [comment]
@aqueenan thanks for sharing your hack, here is mine :)
```js
async function getAsset(event, uri) {
  const ev = Object.assign(
    {
      waitUntil: p => {
        event.waitUntil(p)
      },
    },
    event,
    {
      request: new Request(`${new URL(event.request.url).origin}/${uri}`),
    },
  )

  return getAssetFromKV(ev)
}
```

**Comment by signalnerve** [comment]
Great convo here, can someone open a PR to fix this?
