### ISSUE TITLE
Error in documentation (re: ETags)

### ISSUE THREAD

**Issue by aaronpeters** [cloudflare/kv-asset-handler#152]
https://github.com/cloudflare/kv-asset-handler#cache-revalidation-and-etags

https://www.cdnplanet.com/ uses Workers Sites and no responses are served with an ETag.
My worker script is **not** setting `bypassCache: true`

Is the documentation indeed wrong and it's correct that Cloudflare does not serve ETag header on my site's responses?

**Comment by SukkaW** [comment]
The ETag issue has been fixed in https://github.com/cloudflare/kv-asset-handler/pull/133. The PR is waiting for review now.

**Comment by aaronpeters** [comment]
Thanks @SukkaW 
I was just reading up on the relevant issues and arrived at #133 when I noticed your comment in this issue.

**Comment by Cherry** [comment]
I believe with #133 and the release of `0.1.2` this should now be resolved. I'm seeing expected etag responses on various sites I've updated personally. Feel free to re-open this issue if you run into any further problems!
