### ISSUE TITLE
Serve different assets any given `requestKey`, even if those are in the `ASSET_MANIFEST`

### ISSUE THREAD

**Issue by Cherry** [cloudflare/kv-asset-handler#158]
It would be awesome if we could "hijack" requests and serve different assets to that request, even if that filename exists in the `ASSET_MANIFEST`. An immediate use-case for this would be to serve newer image formats to clients that support them, such as WebP or AVIF images, even when a JPEG is requested.

The `mapRequestToAsset` would be perfect for this use-case, if it allowed this function to entirely override the `requestKey`. The code in this file doesn't seem to support this though: https://github.com/cloudflare/kv-asset-handler/blob/3228cd78de1f4f61d74cecb13a3b19054d67d501/src/index.ts#L104-L110. I don't really understand what the impact would be by always using the `mapRequestToAsset` if a custom one was defined for this request, but that would be a possible solution here.

Pseudo-code example if this were possible:
```js
// handle images rewrite to webp
if(url.pathname.match(imageRegex)){
	// request for an image. Check if we can serve webp instead
	if(event.request.headers.has('accept') && event.request.headers.get('accept').match(/image\/webp/)){
		options.mapRequestToAsset = (request) => {
			const parsedUrl = new URL(request.url);
			parsedUrl.pathname = parsedUrl.pathname.replace(imageRegex, '.webp');
			return new Request(parsedUrl.toString(), request);
		};
	}
}
```

Note: This actually used to work in much older versions of `kv-asset-handler`: https://github.com/cloudflare/kv-asset-handler/blob/ce0229fe54e38728b2d7796646e20a05ea23b6d1/src/index.ts#L98. This was changed in https://github.com/cloudflare/kv-asset-handler/commit/c97b8ddf118b8711bc1cc9408461a1c47a1843be though.

Let me know if I can provide any more info here!

**Comment by SukkaW** [comment]
https://github.com/cloudflare/kv-asset-handler#helper-functions

**Comment by Cherry** [comment]
> [cloudflare/kv-asset-handler#helper-functions](https://github.com/cloudflare/kv-asset-handler#helper-functions)
> 
> It seems that we have already provided an example of how to use it (correctly).

I apologise if I'm misunderstanding, but the `mapRequestToAsset` isn't actually helpful in this case. As per the description in my issue and the code at https://github.com/cloudflare/kv-asset-handler/blob/3228cd78de1f4f61d74cecb13a3b19054d67d501/src/index.ts#L104-L110, if the image exists in the manifest, the `mapRequestToAsset` function is never fired to intercept this.

So for example if I had an `image.png`, `image.webp` and `image.avif` in my manifest, and wanted to dynamically serve the `webp` or `avif` to supported clients when they requested the `image.png`, there's no simple way to do this today. In an [older version](https://github.com/cloudflare/kv-asset-handler/blob/ce0229fe54e38728b2d7796646e20a05ea23b6d1/src/index.ts#L98) of `kv-asset-handler` that _always_ called `mapRequestToAsset`, this was possible.

A work-around that was suggested that I feel could work is be completely reconstructing the `FetchEvent` with a newly constructed `Request` `request` property that's passed into the `getAssetFromKV` function, though this is extremely hacky.

**Comment by Cherry** [comment]
I'd happily create a PR and even add some tests for this functionality to ensure no future regressions if it makes sense. I just want to make sure I understand the impact.

From what I can tell, it should be pretty simple to tweak the `getAssetFromKV` function, switch up the `Object.assign` at the top for defaults, handling `mapRequestToAsset`'s default more manually. And then below when assigning `requestKey`, check if `options.getAssetFromKV` was explicitly passed in (not from default), and if so use that, else do the existing behaviour. Would this be a PR that's accepted?
