### ISSUE TITLE
kv-asset-handler can translate 206 responses to 200 responses

### ISSUE THREAD

**Issue by harrishancock** [cloudflare/kv-asset-handler#165]
TL;DR: I think this line should preserve whatever response status code `cache.match()` returned: https://github.com/cloudflare/kv-asset-handler/blob/3228cd78de1f4f61d74cecb13a3b19054d67d501/src/index.ts#L206

Originally reported by @willbicks here: https://github.com/cloudflare/wrangler/issues/1746

For a fuller investigation, please read: https://community.cloudflare.com/t/pdfs-downloaded-from-cfworkers-wrangler-corrupted/238857/10

@shagamemnon I think you worked on this code previously -- would you mind taking a look? Is the fix as easy as I hope it is?

**Comment by shagamemnon** [comment]
I don't think that changing this to:
```
new Response(response.body, { headers, status: response.status })
```
... will create any new problems and it will probably solve this one. Will need to check the spec to ensure the changes made to the response headers here will fulfill range requests

**Comment by shagamemnon** [comment]
Something else to bear in mind that I realized while trying to write a test: #133 which enables etag support for all resource types hasn't been merged. When a strong `etag` is presented, partial responses to byte range requests are cached. However when weak `etags` are served, partial responses to range requests are not cached.

I'm not certain of all the resource types that will gain etag support when #133 is merged but it warrants investigation of cache behavior on CF, Chromium and Safari
