### ISSUE TITLE
/(non-ascii)/index.html cannot be referenced if index.html is omitted

### ISSUE THREAD

**Issue by fu-sen** [cloudflare/kv-asset-handler#169]
I tried to publish a Hugo site with a Japanese URL on Workers Sites, but it returned Not Found.
For example: `https://example.com/日本語/` to `/日本語/index.html`

![スクリーンショット 2021-03-14 22 31 26](https://user-images.githubusercontent.com/5434159/111070700-30d56c00-8516-11eb-87ee-f703fd5ccb01.jpg)

![スクリーンショット 2021-03-14 22 38 02](https://user-images.githubusercontent.com/5434159/111070704-35018980-8516-11eb-95cb-ff9bf16ba1f6.jpg)

Since `https://example.com/日本語/index.html`  can be can be displayed. If you specify other files, they can be displayed.

![スクリーンショット 2021-03-14 22 32 02](https://user-images.githubusercontent.com/5434159/111070726-4cd90d80-8516-11eb-9ce5-b8bd943c7274.jpg)

It was previously pointed out in a pull request, but it hasn't been merged:
https://github.com/cloudflare/kv-asset-handler/pull/142

**Comment by signalnerve** [comment]
Working with the author of #142 to get that issue moving again, thanks for filing!

**Comment by fu-sen** [comment]
Thank you to the corresponding. Because this effect is affected in some areas. Many would prefer the ascii directory.
But I got this improved and am ready to use the Cloudflare Workers Site. 💻☕

**Comment by Cherry** [comment]
This appears to be fixed with the release of `0.1.2` thanks to #142:
![](https://up.jross.me/xb2q8ja0)

Feel free to re-open or create a new issue if you run into anything else!

**Comment by fu-sen** [comment]
Thank you for dealing with it! I have moved some of the Japanese directory websites and blogs to the Workers Site. It's working perfectly! Of course, Chinese and Korean sites will also work. Now more people can use it.
