### ISSUE TITLE
Not compatible with the new ES6 module worker format

### ISSUE THREAD

**Issue by PeterCxy** [cloudflare/kv-asset-handler#174]
It seems that this package still has the assumption of the old worker format (e.g. global environment variables, `FetchEvent`, etc) and does not work properly with the new ES6 module format. I would like to use Durable Objects, which requires the new ES6 module format, in a Workers Site project, and `wrangler` already has a patchset for Workers Site support with the new ES6 module format, and the fact that this package does not support the new format seems to be the last blocker.

**Comment by frandiox** [comment]
Same here, trying to implement the new custom builds in Vitedge but all calls to `getAssetFromKV` throw 500 internal errors.

**Comment by signalnerve** [comment]
> wrangler already has a patchset for Workers Site support with the new ES6 module format

can you link me to this?

Tagged this as `help wanted` - we're going to work on a release this week that probably _won't_ include this unless someone would like to contribute a PR, but I'll mark this as next up for the release after that one 👍

**Comment by ttraenkler** [comment]
@signalnerve i've patched the immediate roadblocker in the above PR #188 - please have a look if that's a suitable fix.

**Comment by ttraenkler** [comment]
Note I merely patched the crash blocking us, but a proper solution would probably pass the env object as a third parameter or similar. however i didn't want to mix this fix with a necessary discussion about how to change the public API going forward. would be nice if this could be released as a fix asap, at least in some esm branch on npm as it complicates the build process for us.

**Comment by Cherry** [comment]
Related wrangler issue: https://github.com/cloudflare/wrangler/issues/1938

**Comment by DrewRidley** [comment]
For one method, ``getAssetFromKV``, the fix appears quite trivial. It should be as simple as creating an override that accepts arguements, ``request, options, context`` as opposed to ``event``. Since the only two properties of ``event`` used were ``waitUntil`` and ``request``, they can be substituted with ``request`` and ``context.waitUntil`` instead. This would improve compatibility with ES6 module workers. I am happy to submit a PR with this change, but I am unfamiliar with the PR process for this repository.

**Comment by DrewRidley** [comment]
Please have a look at my PR, I introduce a fix for this problem. Sadly, the following problem will still cause problems when you try to deploy your site:
https://github.com/cloudflare/wrangler/issues/1938.
I looked into that issue but could not diagnose the issue. Regardless, this should not have an impact on the ability to merge my PR.

**Comment by threepointone** [comment]
We're cutting a release on both wrangler and kv-asset-handler that should provide a path forward. I'll send a PR documenting how very soon.

**Comment by threepointone** [comment]
released, with the readme updated, we'll update the official docs as well soon.
