### ISSUE TITLE
0.1.3 release not published to NPM

### ISSUE THREAD

**Issue by irvinebroque** [cloudflare/kv-asset-handler#196]
Looks like 0.1.3 has been [released](https://github.com/cloudflare/kv-asset-handler/releases/tag/v0.1.3) but not yet published to NPM: 

https://www.npmjs.com/package/@cloudflare/kv-asset-handler

Will it be published soon? Looking to upgrade to get unblocked from this issue: https://github.com/cloudflare/kv-asset-handler/issues/174

**Comment by irvinebroque** [comment]
Looks like the version wasn't updated in `package.json`:

https://github.com/cloudflare/kv-asset-handler/blob/master/package.json#L3

**Comment by Cherry** [comment]
We're working on getting this released soon. 👍

**Comment by Cherry** [comment]
This has now been published to npm. Thanks for your patience!
