### ISSUE TITLE
Falling back to single-page application 404 page for static assets

### ISSUE THREAD

**Issue by taobojlen** [cloudflare/kv-asset-handler#201]
I'm serving an SPA via Cloudflare Workers Sites, roughly as follows:

```js
async function handleEvent(event) {
  let options = {
    mapRequestToAsset: serveSinglePageApp,
  }

  let page
  try {
    page = await getAssetFromKV(event, options)
  } catch (e) {
    if (e instanceof NotFoundError) {
      // Continue and let the SPA show its 404 page
      const { origin } = new URL(event.request.url)
      const request = new Request(`${origin}/index.html`, event.request)
      page = await getAssetFromKV({ ...event, request }, options)
    } else {
      throw e
    }
  }

  const response = new Response(page.body, page)
  // <snip> Set some response headers...
  return response
}
```

The intended behavior is for requests to e.g. `/arbitraryfilename.txt` to show the SPA's "Not found" page. Inside the `catch` block after `getAssetFromKV`, I'm trying to get the root page and serve that (the code is roughly lifted from the `serveSinglePageApp` function).

The problem I'm running into is that the second call to `getAssetFromKV` throws an error:
```
worker.js:1 Uncaught (in promise) TypeError: a.waitUntil is not a function
    at VM3 worker.js:1
    at VM3 worker.js:1
    at Object.next (VM3 worker.js:1)
```

It seems `event.waitUntil` isn't being handled property with the spread operator. Nor is it possible to do `event.request = ...`, since `event` is readonly.

Can anyone point me in the right direction?

**Comment by Cherry** [comment]
Thanks for the question! I'm not entirely sure about spreading `event`, but I think you should be able to refactor this by just modifying the `napRequestToAsset` function on your second call to `getAssetFromKV`, such as this (untested):

```js
async function handleEvent(event){
	let options = {
		mapRequestToAsset: serveSinglePageApp,
	};

	let page;
	try{
		page = await getAssetFromKV(event, options);
	}catch(err){
		if(err instanceof NotFoundError){
			// Continue and let the SPA show its 404 page
			page = await getAssetFromKV(event, {
				mapRequestToAsset: (request) => {
					const {origin} = new URL(event.request.url);
					const newRequest = new Request(`${origin}/index.html`, request);
					return newRequest;
				},
			});
		}else{
			throw err;
		}
	}

	const response = new Response(page.body, page);
	// <snip> Set some response headers...
	return response;
}
```

This makes use of a custom [`mapRequestToAsset`](https://github.com/cloudflare/kv-asset-handler#maprequesttoasset) function, overriding the request key to your specific `index.html` on a `NotFoundError`, which appears to be what you're trying to do in your `catch` block. You may want to modify the response status code to be a 404 too, such as in the [example template](https://github.com/cloudflare/worker-sites-template/blob/dd042daba3d6e1e1da1bd56dbf01be642b4870c3/workers-site/index.js#L50-L55).

**Comment by taobojlen** [comment]
Thanks @Cherry -- using a custom `mapRequestToAsset` function works nicely! I appreciate the help.
