### ISSUE TITLE
Confusing fallback in mapRequestToAssets

### ISSUE THREAD

**Issue by jasonthorsness** [cloudflare/kv-asset-handler#278]
The workers sites documentation suggests you can handle prefixes in a simple way by overriding mapRequestToAsset:

https://github.com/cloudflare/worker-sites-template/blob/master/workers-site/index.js#L23
https://github.com/cloudflare/worker-sites-template/blob/master/workers-site/index.js#L69

However, following this guidance can subtly break things, because the fallback order has a direct lookup in the middle:

1. options.mapRequestToAsset
2. ASSET_MANIFEST[rawPathKey]
3. default mapRequestToAsset

When you override mapRequestToAsset in the suggested way (with a call in your customer mapRequestToAsset to the default mapRequestToAsset) you are removing the #2 direct lookup fallback from consideration. This has the effect of breaking lookups for files with an unrecognized MIME type due to https://github.com/cloudflare/kv-asset-handler/blob/fd27ccfeb541312f5e6c6be74932efc32ae4ce1f/src/index.ts#L59 when a random '.html' gets appended.

Practically, this broke hosting of my static site using [Blazor](https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor) because the site failed to load _framework/dotnet.timezones.blat as it has an unrecognized extension- it was quite confusing when even setting "options.mapRequestToAsset = mapRequestToAsset" (which seems like it should be a NOOP) broke the site.

Not sure how to deal with backwards compatibility here but it would be nice if this worked more intuitively.

**Comment by Cherry** [comment]
I believe the mentality behind this was that if you're passing your own `mapRequestToAsset`, you should be handling all of the lookup and mapping process yourself, acting essentially as an override. You could re-use parts of the default function in your own `mapRequestToAsset` override, such as:
```js
...
const parsedUrl = new URL(request.url)
let pathname = parsedUrl.pathname
if (!mime.getType(pathname)) {
    // If path doesn't look like valid content
    //  e.g. /about.me ->  /about.me/index.html
    pathname = pathname.concat('/' + options.defaultDocument)
}
// any other logic
parsedUrl.pathname = pathname
return new Request(parsedUrl.toString(), request)
```
