### ISSUE TITLE
Content length undefined when edge cache

### ISSUE THREAD

**Issue by gffuma** [cloudflare/kv-asset-handler#290]
When edge cache is enabled content length is `undefined` 

https://github.com/cloudflare/kv-asset-handler/blob/master/src/index.ts#L277
Should be `byteLength` instead of `length` cause is an [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/byteLength) 🤔  ?

**Comment by philipatkinson** [comment]
I believe that is the correct fix - I have a pull request going up today with that change in it. Note that the content-length header is omitted if the response is compressed (e.g content-encoding is set to 'br').
