### ISSUE TITLE
struggling with understanding how to transition from service worker to module

### ISSUE THREAD

**Issue by mrbm** [cloudflare/kv-asset-handler#365]
I've gone through removing webpack and converting my project from a service worker to a module

My last struggle seems to be converting the use of 

to module.

Following the instructions it looks like there are 2 new requirements that I must set

A. Create an environment variable named __STATIC_CONTENT
B. Create a text file named __STATIC_CONTENT_MANIFEST with some sort of json object

However I can not seem to find any documentation that describes when transitioning from a service worker similar to:
response = await getAssetFromKV(event)

There is no full description of what to be doing for A and B listed above.

Can the env variable __STATIC_CONTENT be set to anything? Or is there something specific if coming from a service worker?

Is __STATIC_CONTENT_MANIFEST the name of a text file that should be in the top level directory? And what is an example of the object data that should be in there?

Appreciate the help!

**Comment by mrbm** [comment]
After further reading, if I already have __STATIC_CONTENT kv binding set up then I should be good for question A. But possibly struggling with part B. As it is now, project responds with a 'An unexpected error occurred', { status: 500 } from the example, which leads me to believe I don't have the the static content manifest set up properly

**Comment by Cherry** [comment]
You do not need to setup any kind of manual `__STATIC_CONTENT` or `__STATIC_CONTENT_MANIFEST` as long as you have the `[site]` config in your `wrangler.toml`.

Can you share a minimal reproduction repo to reproduce the issue please?

**Comment by Cherry** [comment]
This was resolved in the Discord. Thanks @mrbm
