### ISSUE TITLE
Browser Cache issue

### ISSUE THREAD

**Issue by victoriabernard92** [cloudflare/kv-asset-handler#38]
Browser cache gets set to edgeTTL on HITS

**Comment by jaydp17** [comment]
The `expires` header from 
https://github.com/cloudflare/kv-asset-handler/blob/master/src/index.ts#L146 is passed on to the browser response headers when `browserTTL = null`.

**Comment by victoriabernard92** [comment]
@jaydp17 could you clarify what behavior that causes? steps to reproduce the problem would help me understand.
