### ISSUE TITLE
Downtime after `wrangler publish`

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/kv-asset-handler#39]
Asset manifest updates much faster than KV, this will make people's pages 404 for a small window while KV updates. We should probably check KV for the thing the asset manifest points to first, but if it's not there, look for the stuff that used to be in kv with like a regex or something

**Comment by ashleymichal** [comment]
we can probably leverage the `listKeys` feature: https://developers.cloudflare.com/workers/reference/storage/listing-keys/

use the prefix to find the key we want first. this may incur a performance penalty, but would reduce downtime to effectively nothing if properly implemented.

**Comment by EverlastingBugstopper** [comment]
So I just tested to see if this happens and I'm not seeing it happen anymore for some reason... KV seems to be updating perfectly. @fernandogrd I saw that you had put a 👍 on this issue, have you run into this recently?

**Comment by bretthoerner** [comment]
If you do this order (serially):

1. Write all assets out
2. Write out the new manifest

You should never see a 404.

I can imagine a couple ways to see a 404:

a. If you race the asset + manifest uploads then anyone seeing the new manifest might 404 on assets they aren't in KV yet.
b. If you do any deletes to clean up no-longer-existing pages, people who see a previous (cached) manifest might see 404s.

**Comment by fernandogrd** [comment]
@EverlastingBugstopper I was waiting for this to be fixed so I could use the static website feature, it was a blocker for me since.
