### ISSUE TITLE
TypeScript declarations on npm

### ISSUE THREAD

**Issue by tchak** [cloudflare/kv-asset-handler#43]
Everything is in the title :) Would be nice to have types. Or should types be part of `@cloudflare/workers-types`?

**Comment by victoriabernard92** [comment]
TS is now supported 😄

**Comment by abiro** [comment]
Hey, 

it seems that the type information doesn't make it into the release. This is the content of the latest tarball on NPM:

```
package/.prettierrc
package/LICENSE_APACHE
package/LICENSE_MIT
package/test/getAssetFromKV.js
package/src/index.js
package/test/mapRequestToAsset.js
package/src/mocks.js
package/test/serveSinglePageApp.js
package/package.json
package/CHANGELOG.md
package/README.md
package/.github/workflows/test.yml

```

**Comment by EverlastingBugstopper** [comment]
cc @victoriabernard92 - we need to be providing types for devs that want to use this library in their own typescript project

**Comment by bsbechtel** [comment]
@EverlastingBugstopper Did you ever figure out how you could add types to your project?

**Comment by victoriabernard92** [comment]
Misread the ask, I think we should add the types to `@cloudflare/workers-types` package. Happy to review a proposed solution or we should look into this.

**Comment by mathiasrw** [comment]
>  error TS2307: Cannot find module '@cloudflare/kv-asset-handler' or its corresponding type declarations.

It would be so nice if you included types. Its literally just a few lines.

**Comment by mathiasrw** [comment]
❤️
