### ISSUE TITLE
Converting server errors to 404 may confuse crawlers and others

### ISSUE THREAD

**Issue by kentonv** [cloudflare/kv-asset-handler#44]
`getAssetFromKV()` currently throws an exception when the key is not found. The documentation and auto-generated code suggest the caller should catch all exceptions and serve a 404 page in response.

I'm concerned, though, that this means other kinds of exceptions -- like transient network errors -- get converted to 404s. Returning a 404 in this case might confuse some clients, especially automated ones. For example, a web crawler knows that if it gets a 500-level error, it should try again later while continuing to index the last version it successfully received. However, if it gets a 404, it may believe the page is gone, evict the page from the index and may not try to fetch it again for some time.

Any thoughts on this?

**Comment by victoriabernard92** [comment]
closed by https://github.com/cloudflare/kv-asset-handler/issues/59
