### ISSUE TITLE
Handling Errors 

### ISSUE THREAD

**Issue by victoriabernard92** [cloudflare/kv-asset-handler#59]
Proposal on how to fix issues like https://github.com/cloudflare/kv-asset-handler/issues/44

## Custom Error class 
I suggest we create a custom error class that looks something like

```
export class KVError extends Error {
  constructor(message?: string, code: number = 500) {
    super(message)
    Object.setPrototypeOf(this, new.target.prototype) // restore prototype chain
    this.name = KVError.name // stack traces display correctly now
    this.code = code
  }
  code: number // Appropriate HTTP status code
}

```

## `getAssetFromKV` throws custom error
`getAssetFromKV` will now throw custom errors that we can identify as `KVError`.

Example inside `getAssetFromKV` 

```
    throw new KVError(`${request.method} is not a valid request method`, 405)
    throw new KVError(`there is no ${ASSET_NAMESPACE} namespace bound to the script`, 500)
```

### Workers sites template
now instead of having [crazy try/catch blocks](https://github.com/cloudflare/worker-sites-template/blob/master/workers-site/index.js#L37-L55) and assuming a 404 error in the sites template, we'd have workers-site-template look like:

```
try {
  let resp = await getAssetFromKV()
  return new Response(resp.message, { status: resp.code })
} catch (e) {
  if (resp instanceof KVError) {
    switch (e.code) {
      case 404:
        return notFoundResponse
        break
      case 401:
        return methodNotAllowedResponse
        break
      default:
        return new Response(resp.message, { status: resp.code })
    }
  }
}

```

## Alternative option: `getAssetFromKV` returns a  custom error

`getAssetFromKV` will now _not throw generated errors_, but instead optionally return `KVError`.

```
const getAssetFromKV: (event..) => Promise<KVError | Response>
```

Examples of returning these errors instead of throwing them:

```
    return new KVError(`${request.method} is not a valid request method`, 405)
    return new KVError(`there is no ${ASSET_NAMESPACE} namespace bound to the script`, 500)
```

**Comment by EverlastingBugstopper** [comment]
i think we should throw the errors rather than returning it so that it is

1) not a breaking change
2) you can use a `switch` statement in the `catch` block on errors, or it can continue to function like it currently does

**Comment by gabbifish** [comment]
I agree with Avery--we should continue throwing errors, given that this is more js-idiomatic and prevents a breaking change in behavior. 

Some critical requirements:
- We should still make sure to return whatever asset is stored at 404.html when we return a 404.
- HTTP codes like 405 don't need bodies, but some like 502 and 401 usually provide a simple plaintext message (e.g. Server `Unavailable`, `Unauthorized` respectively).

**Comment by ashleymichal** [comment]
> HTTP codes like 405 don't need bodies, but some like 502 and 401 usually provide a simple plaintext message (e.g. Server Unavailable, Unauthorized respectively).

iirc, the Response object fills in the default messages on things like that... or perhaps it is the browser that does so.

**Comment by ashleymichal** [comment]
i would be less concerned about breaking changes pre-1.0.0, fwiw. being more idiomatic is for sure good motivation though.

the question i've always had is whether the kv-asset-handler should automatically include the asset found at 404.html (if any) when it throws the NotFound error. developers can use it or not, but that would prevent another round of "was it found?"

**Comment by EverlastingBugstopper** [comment]
> the question i've always had is whether the kv-asset-handler should automatically include the asset found at 404.html (if any) when it throws the NotFound error. developers can use it or not, but that would prevent another round of "was it found?"

I kinda like that - but we should allow the path to be configurable in case people want it to be called something else like `notfound.html`
