### ISSUE TITLE
Range requests aren't handled properly

### ISSUE THREAD

**Issue by shagamemnon** [cloudflare/kv-asset-handler#60]
This bug is described here: https://github.com/cloudflare/wrangler/issues/928.

To summarize, the Cache API can't serve range requests to Safari because the cache key is stripping the client's request headers (namely, the `Range` header). Opening a PR to fix this now

**Comment by shagamemnon** [comment]
https://github.com/shagamemnon/kv-asset-handler/tree/frank/support-range-requests

**Comment by b0ric** [comment]
Range requests still do not work in Safari as of `0.1.2`

**Comment by shagamemnon** [comment]
@b0ric can we move this discussion to #167?
