### ISSUE TITLE
Understanding default caching

### ISSUE THREAD

**Issue by zackbloom** [cloudflare/kv-asset-handler#70]
Hello! @AustinCorridor ran into an issue where the HTML of his site was being delivered with a Cache-Control TTL of one year, causing it to not update properly for some clients as he changed it. Is this expected behavior of Wrangler / the kv-asset-handler? Thank you!

**Comment by ashleymichal** [comment]
this was a bug in the first version of kv-asset-handler. updating version and re-running npm install in the workers-site directory should fix it for future deploys.

**Comment by zackbloom** [comment]
What's the best way to be apprised of changes like that in the future? What versions are still acceptable for use and what have significant issues?

**Comment by ashleymichal** [comment]
the best record we have for changes we make to our tooling is almost always the changelog: https://github.com/cloudflare/kv-asset-handler/blob/master/CHANGELOG.md

**Comment by ashleymichal** [comment]
but it is likely we should start looking into deprecation schedules and version support documentation.

**Comment by zackbloom** [comment]
Perfect, thanks for letting me know @ashleymichal

**Comment by AustinCorridor** [comment]
Thank y'all. For the record, the real bug here was using the latest version of Hugo. And that's my fault. I'm so sorry for guessing at everything else before I thought about using a new version of Hugo that that included breaking changes for inline HTML with markdown.

https://gohugo.io/news/0.60.0-relnotes/

**Comment by zackbloom** [comment]
The caching was definitely too high for HTML either way. Glad you got it sorted!
