### ISSUE TITLE
serveSinglePageApp can not use with query strings

### ISSUE THREAD

**Issue by sgiacosa** [cloudflare/kv-asset-handler#72]
I have a website in Angular and it is published using workers KV.
With version 0.0.7 I use serveSinglePageApp. It works when the url is like
`mysite.com/buy/item`

but if the url is like 
`mysite.com/buy/item?id=1234`
it get an "could not find buy/item/index.html in your content namespace"

I know that the best design should be buy/item/1234 but i can not manage that because I need to manage externals responses to my site so I can not change that way.

Is any way to solve this?

Thanks in advance!
Sebastián

**Comment by sgiacosa** [comment]
Hello, I got the solution.
The problem is in the function 

```
function serveSinglePageApp(request) {
  // First apply the default handler, which already has logic to detect
  // paths that should map to HTML files.
  request = mapRequestToAsset(request)

  // Detect if the default handler decided to map to
  // a HTML file in some specific directory.
  if (request.url.endsWith('.html')) {
    // If expected HTML file was missing, just return the root index.html
    return new Request(`${new URL(request.url).origin}/index.html`, request)
  } else {
    // The default handler decided this is not an HTML page. It's probably
    // an image, CSS, or JS file. Leave it as-is.
    return request
  }
}
```

I changed to 

```
function serveSinglePageApp(request) {
  // First apply the default handler, which already has logic to detect
  // paths that should map to HTML files.
  request = mapRequestToAsset(request)

    **const parsedUrl = new URL(request.url)**    
    
  // Detect if the default handler decided to map to
  // a HTML file in some specific directory.
  **if (parsedUrl.pathname.endsWith('.html')) {**
    // If expected HTML file was missing, just return the root index.html
    return new Request(`${new URL(request.url).origin}/index.html`, request)
  } else {
    // The default handler decided this is not an HTML page. It's probably
    // an image, CSS, or JS file. Leave it as-is.
    return request
  }
}
```

**Comment by jordanvector** [comment]
Had the same issue, this^ solved it

**Comment by signalnerve** [comment]
ah thanks! the provided solution totally makes sense. i'll work up a PR for this, thanks @sgiacosa!

**Comment by EatonZ** [comment]
Hi all, ran into this as well and I'm glad to see it's already fixed! When can we expect an update to be published on npm?🙂

**Comment by abury** [comment]
Looks like this is still an issue? Ran into this with a fairly new app.

**Comment by signalnerve** [comment]
@abury it shouldn't be! if you've made an app using `wrangler generate --site` or `wrangler init --site` make sure that your `kv-asset-handler` version in `package.json` is up-to-date: 0.0.11 at time of writing.

**Comment by abury** [comment]
@signalnerve Yeah i had to jump in and bump up the version of kv-asset-handler manually, but once I did that it was all good 👍
