### ISSUE TITLE
URL rewrite with `getAssetFromKV`

### ISSUE THREAD

**Issue by abiro** [cloudflare/kv-asset-handler#74]
Hi,

I'm writing a middleware for Cloudflare Workers that checks some conditions in the incoming request and rewrites the URL if those conditions are met.

I can construct a new `Request` with a modified URL, but I couldn't find a way to pass the modified URL to `getAssetFromKV`, because it takes a `FetchEvent` as argument and it's not possible to construct a new `FetchEvent` in workers or to mutate the `FetchEvent.request` property. So I thought a possible solution would be if I could pass a `urlOverwrite` option to  `getAssetFromKV` in which case the function would use that URL instead of the `event.request.url`. 

Happy to provide a PR for the `urlOverwrite` option or even more happier if you can suggest a better solution. :)

Best,
Agost

**Comment by EverlastingBugstopper** [comment]
Hey @abiro, we provide that functionality now with the [`mapRequestToAsset`](https://github.com/cloudflare/kv-asset-handler#maprequesttoasset) function which takes in a `Request`. Hopefully that helps!

**Comment by abiro** [comment]
Great, thanks!
