### ISSUE TITLE
Different browser cache max-age for HTML and assets

### ISSUE THREAD

**Issue by abiro** [cloudflare/kv-asset-handler#81]
Hi,

I'd like to have a different browser cache max-age for HTML and assets. Is this possible somehow or does it need a change to the library?

Thanks,
Agost

**Comment by Cherry** [comment]
You can simply override `options.cacheControl` for specific files/extensions, or set it after retrieving the file from KV. For example:

```js
const options = {
	cacheControl: {
		edgeTTL: 60 * 60 * 1, // 1 hour
		browserTTL: 60 * 60 * 1, // 1 hour
		bypassCache: false
	}
};
const filesRegex = /(.*\.(ac3|avi|bmp|br|bz2|css|cue|dat|doc|docx|dts|eot|exe|flv|gif|gz|htm|html|ico|img|iso|jpeg|jpg|js|json|map|mkv|mp3|mp4|mpeg|mpg|ogg|pdf|png|ppt|pptx|qt|rar|rm|svg|swf|tar|tgz|ttf|txt|wav|webp|webm|webmanifest|woff|woff2|xls|xlsx|xml|zip))$/;

// override cache to 30 days for files
if(url.pathname.match(filesRegex)){
	options.cacheControl.edgeTTL = 60 * 60 * 24 * 30; // 30 days
	options.cacheControl.browserTTL = 60 * 60 * 24 * 30; // 30 days
}

return await getAssetFromKV(event, options);
```

Or, store the result of `getAssetFromKV` in a variable like `asset`, and do something like this:

```js
if(asset && asset.headers && asset.headers.get('content-type') === 'text/html'){
	asset.headers.set('cache-control', 'public, max-age 3600');
}
```

I do something similar over at https://github.com/Cherry/placeholders.dev, where I cache generated images for 90 days, other images and static files for 30 days, and everything else for shorter periods of time.

**Comment by abiro** [comment]
Great, thanks!
