### ISSUE TITLE
Serving assets/SPA with http2

### ISSUE THREAD

**Issue by antonsamper** [cloudflare/kv-asset-handler#84]
I'm using the `getAssetFromKV` and `serveSinglePageApp` to serve my single page app and thats working well so far but I've noticed that all assets are being server via `http/1.1`. I was wondering if there was a way to serve the SPA and assets using `http/2`?

**Comment by EverlastingBugstopper** [comment]
Hey @antonsamper - you should be able to enable HTTP/2 in the Cloudflare Dashboard by clicking ${your-site.com} -> Network tab -> HTTP/2 On
![image](https://user-images.githubusercontent.com/9408157/76876931-aeea2e80-6840-11ea-809b-7b6296cb1186.png)

**Comment by antonsamper** [comment]
@EverlastingBugstopper thanks for the tip. I've just checked on my side and the option is disabled.

![image](https://user-images.githubusercontent.com/102233/76879604-621d4c80-686e-11ea-8ae0-86945271478a.png)


I have found the following thread but theres no indication as to when it will be enabled again:

https://community.cloudflare.com/t/is-http-2-server-push-disabled/5577

**Comment by EverlastingBugstopper** [comment]
Hey @antonsamper - so it looks like it's enabled there even though the toggle isn't clickable for you. HTTP/2 should be working as intended with that toggle, could you let me know what endpoint you're testing and what HTTP client you're using?

**Comment by antonsamper** [comment]
@EverlastingBugstopper looks like this was user error on my behalf! 😬

You're right, it's enabled already. The issue was with the service worker I had installed. If I unregister the service worker I can see that a fresh fetch gives me the correct protocol:

![image](https://user-images.githubusercontent.com/102233/76883289-d3abc980-6873-11ea-99c5-dba879405222.png)

But subsequent request are cached locally on my browser (via the service worker) and are displayed as having `http/1.1` in Chrome Dev Tools.

Thanks for your help!
