### ISSUE TITLE
Add ability to change fallback path on serveSinglePageApp function

### ISSUE THREAD

**Issue by spentaur** [cloudflare/kv-asset-handler#87]
Right now the default fallback path for the `serveSinglePageApp` helper function is `${parsedUrl.origin}/index.html` which works great for single page apps where there's only one entry to the site, that being `index.html`. However, frameworks such as [NuxtJS](https://nuxtjs.org/) generate multiple entry points, making the [default fallback html page](https://nuxtjs.org/api/configuration-generate/#fallback) `200.html`. It would just be nice to have a way to change the file that `serveSinglePageApp` is looking for.

My current `handleEvent` function is similar to:
```
let options = {
    mapRequestToAsset: (request) => {
      // First apply the default handler, which already has logic to detect
      // paths that should map to HTML files.
      request = mapRequestToAsset(request)

      const parsedUrl = new URL(request.url)

      // Detect if the default handler decided to map to
      // a HTML file in some specific directory.
      if (parsedUrl.pathname.endsWith('.html')) {
        // If expected HTML file was missing, just return the root index.html
        return new Request(`${parsedUrl.origin}/200.html`, request)
      } else {
        // The default handler decided this is not an HTML page. It's probably
        // an image, CSS, or JS file. Leave it as-is.
        return request
      }
    }
  }

  return await getAssetFromKV(event, options)
```

But since I'm copying the function just to change one line, what I want to do is something like:

```
let options = {
  mapRequestToAsset: serveSinglePageApp,
  fallback: '200.html'
}
  return await getAssetFromKV(event, options)
```

I'm personally not sure the best way to achieve this, but I think adding it to options and then passing it to the `const requestKey = ASSET_MANIFEST[rawPathKey] ? request : options.mapRequestToAsset(request)` line would work.

**Comment by Cherry** [comment]
This should now be released and available in `0.1.2` by setting `defaultDocument`. See https://github.com/cloudflare/kv-asset-handler#defaultdocument-optional or #161 for more info.

 Feel free to update this issue if you have any issues!
