### ISSUE TITLE
`getAssetFromKV` example is broken

### ISSUE THREAD

**Issue by tillkruss** [cloudflare/kv-asset-handler#93]
https://github.com/cloudflare/kv-asset-handler#getassetfromkv

In the README example `resp` is undefined and `NotFoundError` is never imported.

```js
import { getAssetFromKV } from '@cloudflare/kv-asset-handler'

addEventListener('fetch', event => {
  event.respondWith(handleEvent(event))
})

async function handleEvent(event) {
  if (event.request.url.includes('/docs')) {
    try {
      return await getAssetFromKV(event)
    } catch (e) {
        switch (typeof resp) {
          case NotFoundError: 
            //..
          case MethodNotAllowedError:
            // ...
          default:
            return new Response("An unexpected error occurred", { status: 500 })
        }
      }
    }
  } else return fetch(event.request)
}
```

**Comment by SukkaW** [comment]
@victoriabernard92
@EverlastingBugstopper 

Don't you guys never notice this?

**Comment by SukkaW** [comment]
Also, someone please told me if `typeof` really can be used for getting the instance of the `Error`?

Do you Cloudflare guys really know how to write JavaScript ???

**Comment by EverlastingBugstopper** [comment]
Hi @SukkaW - glad you're trying out Workers Sites and starting to contribute on this repository.

I would love for you to check out our [code of conduct](https://github.com/cloudflare/kv-asset-handler/blob/master/CODE_OF_CONDUCT.md) before further interacting here, as we will not tolerate insults towards the maintainers of this, or any other codebase.
