### ISSUE TITLE
Non ASCII path returned 404

### ISSUE THREAD

**Issue by SukkaW** [cloudflare/kv-asset-handler#99]
Considering a URL: `https://example.com/你好/`:

```js
const url = new URL('https://example.com/你好/');
url.href;
// "https://example.com/%E4%BD%A0%E5%A5%BD/"
url.pathname;
// "/%E4%BD%A0%E5%A5%BD/"
```

But during `wrangler publish`, the file will be stored using original name in Workers KV:

![image](https://user-images.githubusercontent.com/40715044/83711145-fc628480-a654-11ea-8480-47a15f6abcf9.png)

https://github.com/cloudflare/kv-asset-handler/blob/eb120a4b789282e4c44ff8b95e2dd2e220b83e6d/src/index.ts#L100-L104

Thus the `url.pathname` should be `decodeURI` before being used as `rawPathKey`.

This should be considered as a critical bug (It will cause every non-ascii URL path to be 404) and an emergency fix should be released.

**Comment by SukkaW** [comment]
#100 is opened to fix the issue.

**Comment by harrishancock** [comment]
We should re-open this. I think a correct fix will have to be opt-in per user, since we can't assume that all users want to percent-decode URLs.

**Comment by fu-sen** [comment]
It was a response over a year. (No, actually even earlier)
I grabbed the complete pattern of this problem and reported it to Issue. https://github.com/cloudflare/kv-asset-handler/issues/169
Recently this source has been merged. I can see that I work on Japanese blogs and websites. Of course it will work in Chinese as well. Thank you for your support!
